export const post = [
  {
    id: 1,
    x: 74,
    y: 7,
    q: "What Blockchain do you use?",
    a: "What Blockchain do you use? What Blockchain do you use?",
  },
  {
    id: 2,
    x: 11,
    y: 21,
    q: "What Blockchain do you use?",
    a: "What Blockchain do you use? What Blockchain do you use?",
  },
  {
    id: 3,
    x: 38,
    y: 12,
    q: "What Blockchain do you use?",
    a: "What Blockchain do you use? What Blockchain do you use?",
  },
  {
    id: 4,
    x: 43,
    y: 39,
    q: "What Blockchain do you use?",
    a: "What Blockchain do you use? What Blockchain do you use?",
  },
  {
    id: 1,
    x: 13,
    y: 41,
    q: "What Blockchain do you use?",
    a: "What Blockchain do you use? What Blockchain do you use?",
  },
  {
    id: 2,
    x: 70,
    y: 50,
    q: "What Blockchain do you use?",
    a: "What Blockchain do you use? What Blockchain do you use?",
  },
  {
    id: 3,
    x: 52,
    y: 5,
    q: "What Blockchain do you use?",
    a: "What Blockchain do you use? What Blockchain do you use?",
  },
  {
    id: 4,
    x: 43,
    y: 64,
    q: "What Blockchain do you use?",
    a: "What Blockchain do you use? What Blockchain do you use?",
  },
  {
    id: 1,
    x: 73,
    y: 29,
    q: "What Blockchain do you use?",
    a: "What Blockchain do you use? What Blockchain do you use?",
  },
  {
    id: 2,
    x: 56,
    y: 22,
    q: "What Blockchain do you use?",
    a: "What Blockchain do you use? What Blockchain do you use?",
  },
];
